stages:
  - build

build-windows-32bit-client:
  stage: build
  image: dockcross/windows-x86
  script:
    - make ARCH=x86 BUILD_CLIENT=1
    - ls -l build/release-mingw32-x86_64
  artifacts:
    paths:
      - build/release-mingw32-x86_64/quake3e*

build-windows-64bit-client:
  stage: build
  image: dockcross/windows-x64
  script:
    - make ARCH=x86_64 BUILD_CLIENT=1
    - ls -l build/release-mingw64-x86_64
  artifacts:
    paths:
      - build/release-mingw64-x86_64/quake3e*

build-linux-64bit-server:
  stage: build
  image: teeks99/clang-ubuntu:12
  script:
    - BUILD_SERVER=1 make
  artifacts:
    paths:
      - apt install -y make gcc libcurl4-openssl-dev mesa-common-dev libxxf86dga-dev libxrandr-dev libxxf86vm-dev libasound-dev libsdl2-dev
      - build/release-linux-x86_64/quake3e*
      - ls -l build/release-linux-x86_64