stages:
  - build

build-windows-32bit-client:
  stage: build
  image: thewtex/cross-compiler-windows-x86
  script:
    - make ARCH=x86 BUILD_CLIENT=1 BUILD_SERVER=0
    - ls -l build/release-mingw32-x86_64
  artifacts:
    paths:
      - build/release-mingw32-x86_64/quake3e*

build-windows-64bit-client:
  stage: build
  image: mmozeiko/mingw-w64
  script:
    - make ARCH=x86_64 BUILD_CLIENT=1
    - ls -l build/release-mingw64-x86_64
  artifacts:
    paths:
      - build/release-mingw64-x86_64/quake3e*

build-linux-64bit-server:
  stage: build
  image: teeks99/clang-ubuntu:12
  script:
    - apt update -y
    - apt install -y make gcc libcurl4-openssl-dev mesa-common-dev
    - apt install -y libxxf86dga-dev libxrandr-dev libxxf86vm-dev libasound-dev
    - apt install -y libsdl2-dev
    - BUILD_SERVER=1 make
    - ls -l build/release-linux-x86_64
  artifacts:
    paths:
      - build/release-linux-x86_64/quake3e*